services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATASOURCE_DB}
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - authnet

  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DATASOURCE_DB}?stringtype=unspecified
      SPRING_DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_FLYWAY_LOCATIONS: "classpath:db/migration"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "none"
      JWT_SECRET: "${JWT_SECRET}"
      JWT_EXPIRATION: 604800000
    ports:
      - "8080:8080"
    restart: on-failure
    networks:
      - authnet

volumes:
  db-data:

networks:
  authnet:
    driver: bridge